[API] Console Application for Calculating Travel Time
RoqayaAlmamari/GoogleDistanceMatrixAPI pull request #1
Opened 2023-03-02 04:59 UTC by RoqayaAlmamari

2023-03-02 06:51 UTC, BaraahAlKalbani commented on src/main/java/org/example/GoogleDistanceMatrixAPI.java
>      System.out.println("Enter pickup location:");
use the main class (args) instead of getting the value from the user

2023-03-02 06:53 UTC, BaraahAlKalbani requested changes
great work But try to change your code according to my previous comment

2023-03-02 10:37 UTC, BaraahAlKalbani approved these changes
Great Work 👍🏻

2023-03-02 10:50 UTC, WasanMoosa approved these changes
Great work!, you can also implement classes, so each one has single responsibility.

2023-03-05 06:29 UTC, AnwaarAlbusaidi approved these changes
well done, try to use SRP.

2023-03-05 10:04 UTC, closed without merging